### ISSUE TITLE
ruTorrent settings, move, extract

### ISSUE THREAD

**Issue by TheMeeks** [linuxserver/docker-templates#175]
The last 2 docker releases for ruTorrent on unraid have had issues.  The current version, no longer automatically moves torrents from incoming to completed, it no longer extracts if required, is no longer listening on configured port, and spits out an error when trying to open the settings through the GUI.

I suspect that these are all related to the setting error, as manually moving the torrents with the "save to" menu option, as well as the extracting manually with the "Unpack" menu option both work.

I get the following error when clicking on "settings" in the GUI

[27.02.2020 11:52:08] Bad response from server: (500 [error,getsettings]) Warning: XMLRPC call is failed.

**Comment by CHBMB** [comment]
This is the template repo.
