### ISSUE TITLE
WEB UI Needs to be https

### ISSUE THREAD

**Issue by malvarez00** [linuxserver/docker-templates#215]
The current WebUI is: http://[IP]:[PORT:8080]

It needs to be https

**Comment by j0nnymoe** [comment]
Right ok, but for with template?

**Comment by malvarez00** [comment]
The unraid template

**Comment by Roxedus** [comment]
There is over a hundred templates here, you have to tell us which application.

**Comment by malvarez00** [comment]
> There is over a hundred templates here, you have to tell us which application.

Pydio-Cells
