### ISSUE TITLE
Add Medusa support

### ISSUE THREAD

**Issue by OmgImAlexis** [linuxserver/docker-templates#28]
I'm not sure if this is the best place to request this but I don't check UNRAID as much as I check Github.

You may have heard a while back SickrageTV split into Sickrage and then into Medusa.
Medusa requires a URL change for the container and mediainfo installed. Is there any chance you could please add this as a supported container like sickrage and sickbeard?

Ref: https://github.com/pymedusa/Medusa/issues/1841

**Comment by sparklyballs** [comment]
asked a question on the git issue you linked to.

gonna close this issue on this repository.
