### ISSUE TITLE
docker-templates.json for armhf repo

### ISSUE THREAD

**Issue by reey** [linuxserver/docker-templates#98]
This is probably the wrong place to request this, but the OMV Docker GUI component uses the the docker-templates.json file available here: https://tools.linuxserver.io/docker-templates.json to look for updated Docker Images as you can see here: https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-docker-gui/blob/e0ad1fdbd6e2b787c80a7209fb42bd605a051d87/usr/share/openmediavault/engined/rpc/docker.inc#L1602
The problem is, that OMV is only able to find the x86 Docker image updates, because only those are available in this file..
I would like to add a way to perform the same updates on the arm platform as on x86.
Is there an equivalent version of this file for the ARM specific Images available at https://hub.docker.com/u/lsioarmhf/ ?
If not, would it be possible to either add the armhf templates to the existing files or to create a new file with the armhf/arm64 templates?

Thanks reey

**Comment by j0nnymoe** [comment]
This has always been an issue as the json file is based off our unRAID feeds which is x86 only. Though we are currently working on migrating our containers to a new format so they are multi arch and only require one repo. Once this has been completed, the lsioarmhf/aarch64 repo's will be removed.

Unfortunately there isn't an ETA on this but it's in progress :)
